fix(tests): TestIssueService_GetEditMeta_Fail fails on windows due to error message checking
We check the error string in TestIssueService_GetEditMeta_Fail.
On different operting systems, this error message is different. See

- Linux: TestIssueService_GetEditMeta_Fail: metaissue_test.go:456: Error Get "http://127.0.0.1:65328/rest/api/2/issue/PROJ-9001/editmeta": dial tcp 127.0.0.1:65328: connect: connection refused
- Windows: Error Get "http://127.0.0.1:50122/rest/api/2/issue/PROJ-9001/editmeta": dial tcp 127.0.0.1:50122: connectex: No connection could be made because the target machine actively refused it.

Now we check the error type instead of the error message