feat(project): Add GitHub Actions testing workflow (#289)
GitHub actions is a workflow engine.
This testing workflow will
- keep everything inside GitHub (one platform)
- reduce dependency to an external service (TravisCI)
- introduce stricter testing (next to unit tests, staticcheck, fmt, vet)

* fix(tests): TestIssueService_GetEditMeta_Fail fails on windows due to error message checking

We check the error string in TestIssueService_GetEditMeta_Fail.
On different operting systems, this error message is different. See

- Linux: TestIssueService_GetEditMeta_Fail: metaissue_test.go:456: Error Get "http://127.0.0.1:65328/rest/api/2/issue/PROJ-9001/editmeta": dial tcp 127.0.0.1:65328: connect: connection refused
- Windows: Error Get "http://127.0.0.1:50122/rest/api/2/issue/PROJ-9001/editmeta": dial tcp 127.0.0.1:50122: connectex: No connection could be made because the target machine actively refused it.

Now we check the error type instead of the error message

* chore(tests): Support only the current + the last two versions

go-jira follows Go's Release Policy for testing.
See https://golang.org/doc/devel/release.html#policy

Related #290